version: '3.8'


networks:
  backend_network:
    name: backend_network
volumes:
  pgdata:


services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend:/src
      - /src/node_modules
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend:/backend/
    ports:
      - 8000:8000
    networks:
      - backend_network
    env_file:
      - backend/.env
    depends_on:
      db_back:
        condition: service_healthy


  db_back:
    image: postgres:15.1-alpine
    networks:
      - backend_network
    container_name: db_back
    environment:
      - POSTGRES_DB=crypto
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U postgres -p 5432
      interval: 5s
      timeout: 3s
      retries: 3