"""add unique to name portfolio

Revision ID: 4ca29aa2d379
Revises: db27e798133e
Create Date: 2024-08-20 16:04:54.965228

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ca29aa2d379'
down_revision: Union[str, None] = 'db27e798133e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'portfolio', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'portfolio', type_='unique')
    # ### end Alembic commands ###
